[package]
name = "vo"
version = "0.0.1"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Virtual Observatory standard implementation"
license = "GPL-3.0-only"

[dependencies]
