[package]
name = "vo-sia"
version = "0.0.1"
authors = ["Malik Olivier Boussejra <malik@boussejra.com>"]
description = "Virtual Observatory Simple Image Access 2.0 standard implementation"
license = "GPL-3.0-only"

[dependencies]
hyper = "0.12"
url = "1"
vo-table = { path = "../vo-table" }
